# Generated by Django 5.1.1 on 2025-01-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteremail',
            name='sent_at',
        ),
    ]
