# Generated by Django 5.1.1 on 2025-01-02 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_newsletteremail_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('shipping', 'Shipping Information'), ('returns', 'Returns Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=50, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
