# Generated by Django 5.1.1 on 2024-12-17 12:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_detailed_description_product_how_to_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
