# Generated by Django 5.1.1 on 2024-12-18 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_description_category_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
