# Generated by Django 5.1.1 on 2024-12-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_price_product_base_price_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsize',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
