# Generated by Django 5.1.1 on 2025-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sale_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
