# Generated by Django 5.1.1 on 2025-01-08 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_seo_keywords_product_seo_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
